### ISSUE TITLE
HC non calculées

### ISSUE THREAD

**Issue by francodutch** [royto/linky-card#4]
le sensor ne calcule plus les hc (toutes a 0):
# enedis linky
- platform: myEnedis
  token: !secret enedisGateway_token
  code: !secret enedisGateway_code
  heures_creuses: "[[ '03:00', '08:00'], [ '13:30', '16:30']]"
  hc_cout: 0.1131
  hp_cout: 0.1482
  scan_interval: 3600

**Comment by royto** [comment]
Essaye plutôt cette card https://github.com/saniho/content-card-linky

**Comment by francodutch** [comment]
@royto  merci mais le probleme est deja apparent dans le sensor.myenedis meme:
attribution: ''
version: 1.1.0.1
typeCompteur: consommation
lastUpdate: '2021-01-02T16:45:38.285589'
timeLastCall: '2021-01-02T15:45:38.275493'
yesterday: 47901
last_week: 266278
day_1_HP: 47901
day_2_HP: 58597
day_3_HP: 66319
day_4_HP: 33623
day_5_HP: 37260
day_6_HP: 44884
day_7_HP: 33634
day_1_HC: 0
day_2_HC: 0
day_3_HC: 0
day_4_HC: 0
day_5_HC: 0
day_6_HC: 0
day_7_HC: 0

**Comment by royto** [comment]
Il faut alors créer une issue sur le repo du custom component et non la card

**Comment by francodutch** [comment]
my mistake...sorry

**Comment by royto** [comment]
No pb
